//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSPM_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChangeHistories = new HashSet<ChangeHistory>();
            this.WorkItems = new HashSet<WorkItem>();
            this.Projects = new HashSet<Project>();
            this.Rights = new HashSet<Right>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PositionId { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ChangeHistory> ChangeHistories { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<WorkItem> WorkItems { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Right> Rights { get; set; }
    }
}
