//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSPM_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemGroup
    {
        public WorkItemGroup()
        {
            this.WorkItems = new HashSet<WorkItem>();
        }
    
        public int WorkItemGroupId { get; set; }
        public string Description { get; set; }
        public int OrderNumber { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<WorkItem> WorkItems { get; set; }
    }
}
